apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
spec:
  project: nodejs-demo-project
  source:
    repoURL: 'https://github.com/SanthiyaK/Argocd-mern.git'
    path: frontend/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true